config/routes.rb
DaveForHire::Application.routes.draw do

  root :to => 'pages#index'
  match 'services' => 'pages#services'
  match 'sitemap' => 'pages#sitemap'
  match 'contact' => 'pages#contact'

  resources :blogposts, path: "/notes"

end

app/models/blogpost.rb
class Blogpost < ActiveRecord::Base
  attr_accessible :body, :description, :image_url, :tags, :title

  before_save :generate_slug

  def to_param
    slug
  end

  def generate_slug
    self.slug ||= title.parameterize
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :tags, :title

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController
  http_basic_authenticate_with :name => "dave", :password => "904jones", :except => [:index, :show]

  before_filter :latest_post

  def index
    @blogposts = Blogpost.all.sort.reverse[1..-1]
    @page_title = "Dave Woodall | Part-time Technical Co-founder for hire."
    respond_to do |format|
      format.html
      format.json { render json: @blogposts }
    end
  end



  def show
    @blogpost = Blogpost.find_by_slug!(params[:id])
    @page_title       = @blogpost.title
    @page_description = @blogpost.description
    respond_to do |format|
      format.html
      format.json { render json: @blogpost }
    end
  end



  def new
    @blogpost = Blogpost.new

    respond_to do |format|
      format.html
      format.json { render json: @blogpost }
    end
  end


  def edit
    @blogpost = Blogpost.find_by_slug!(params[:id])
  end



  def create
    @blogpost = Blogpost.new(params[:blogpost])

    respond_to do |format|
      if @blogpost.save
        format.html { redirect_to @blogpost, notice: 'Blogpost was successfully created.' }
        format.json { render json: @blogpost, status: :created, location: @blogpost }
      else
        format.html { render action: "new" }
        format.json { render json: @blogpost.errors, status: :unprocessable_entity }
      end
    end
  end



  def update
    @blogpost = Blogpost.find_by_slug!(params[:id])

    respond_to do |format|
      if @blogpost.update_attributes(params[:blogpost])
        format.html { redirect_to @blogpost, notice: 'Blogpost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blogpost.errors, status: :unprocessable_entity }
      end
    end
  end



  def destroy
    @blogpost = Blogpost.find_by_slug!(params[:id])
    @blogpost.destroy

    respond_to do |format|
      format.html { redirect_to blogposts_url }
      format.json { head :no_content }
    end
  end

  def latest_post
    @newest_post = Blogpost.last
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def portfolio
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_filter :latest_post

  def index
    @page_title = "Dave Woodall | Part-time Technical Co-founder for hire"

  end
  def services;end
  def blog; end
  def sitemap; end

  def latest_post
    @newest_post = Blogpost.last ||= ""
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @post = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(params[:id])
  end

  def edit
  end

  def delete
  end

  def update
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown(text)
    options = [:hard_wrap, :autolink, :fenced_code]
    Redcarpet.new(text, *options).to_html.html_safe
  end
end

app/helpers/blogposts_helper.rb
module BlogpostsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/blogposts/_form.html.haml
= form_for @blogpost do |f|
  - if @blogpost.errors.any?
    #error_explanation
      %h2= "#{pluralize(@blogpost.errors.count, "error")} prohibited this blogpost from being saved:"
      %ul
        - @blogpost.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :tags
    = f.text_field :tags
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :image_url
    = f.text_field :image_url
  .field
    = f.label :description
    = f.text_field :description
  .actions
    = f.submit 'Save'

app/views/blogposts/edit.html.haml
%section.content
  .left-bar
    %h1 Editing blogpost

    = render 'form'

    = link_to 'Show', @blogpost
    \|
    = link_to 'Back', blogposts_path

app/views/blogposts/index.html.haml
%br
%header.notes
  %h1 Thoughts on ABC's
  %h3 (Art & Business && Code)
%section.content
  .left-bar
    .hero
      %h1= @newest_post.title
    .overview
      %p
        = markdown(@newest_post.body[0..199])
        \...
        =link_to "more", "/notes/#{@newest_post.slug}"

    .post-list
      %table
        - @blogposts.each do |blogpost|
          %tr
            %td.post-tag= blogpost.tags
            %td.post-title=link_to blogpost.title, blogpost
  .right-bar
    %br
    = render 'shared/more_than_freelancer'
    = render 'shared/he_can'

app/views/blogposts/new.html.haml
%section.content
  .left-bar
    %h1 New blogpost

    = render 'form'

    = link_to 'Back', blogposts_path

app/views/blogposts/show.html.haml
%br
%header
  %h1= @blogpost.title
%section.content
  .left-bar
    .blog-body
      %p
        = markdown(@blogpost.body)
        .signature= image_tag "signature.png"

    .tags
      %p
        Category:
        = @blogpost.tags
        \|
        = link_to "all posts", blogposts_path
        = render 'shared/disqus'

  .right-bar
    %h3
      Other
      = @blogpost.tags
      Posts

    %br
    = render 'shared/more_than_freelancer'
    = render 'shared/he_can'

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    = display_meta_tags
    =render 'shared/analytics'
    =render 'shared/typekit'
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    .container
      = render 'shared/nav'
      = yield
      = render 'shared/footer'

app/views/layouts/pages.html.haml
!!! 5
%html
  %head
    = display_meta_tags
    =render 'shared/analytics'
    =render 'shared/typekit'
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    .container
      = render 'shared/nav'
      = yield
      = render 'shared/footer'

app/views/main/index.html.haml
%nav.links
  %ul
    %li= link_to "portfolio", '#portfolio', class: 'dynamic'
    %li|
    %li= link_to "resume", '#resume', class: 'dynamic'


.work-status
  %p.date= "As of #{Time.now.strftime("%A, %B %e")}"
  %p.status I'm available for Full Time.

%section.overview.row-fluid
  .profile-image=image_tag "me.jpg", id: 'me'
  %h1 Dave Woodall
  %h2 Boulder, CO
  %h3 Ruby on Rails Developer.

%section.dynamic-slide
  %section.resume#resume
    .row.res-title
      %h1 Education
      .row-fluid
        .span11.education-details
          %h2 Starter League (Chicago, IL)
          %h3 Ruby on Rails Training
          %h4 Completed June, 2012
      .row-fluid
        .span11.education-details
          %h2 University of Denver
          %h3 Masters of Finance
          %h4 Graduated June, 2011
      .row-fluid
        .span11.education-details
          %h2 Liberty University (Lynchburg, VA)
          %h3 Communications, Advertising
          %h4 Graduated December, 2000

    .row.res-title
      %h1 Experience

      .row-fluid
        .span11
          %h2 Ruby on Rails Developer
          %h3 Factory Code Labs
          %h4 November '12 - March '13
          %p.summary Summary: Jr. Ruby on Rails Developer
          %p Full time Ruby on Rails developer.

      .row-fluid
        .span11
          %h2 Unofficial Intern
          %h3 Pivotal Labs
          %h4 September '12 - November '12 (3 months)
          %p.summary Summary: Ruby on Rails immersion.
          %p Spent 12 hours a day learning to code surrounded by some of the smartest developers on the planet.
      .row-fluid
        .span11
          %h2 CEO & CO-Founder
          %h3 AMB3R, LLC
          %h4 April '08 - July '12 (4 years 3 months) - <span style="color:red">SOLD!</span>
          %p.summary Summary: Started company with a vision to become the ‘Starbucks of t-shirts’.
          %p Launched business with an innovative product offering and unique approach to custom apparel. Collaborated with vendors to develop a JIT model that responds to orders based on market trends. As interim COO, developed lean systems in the core business that reduced costs increased speed to market with preemptive customer service.
      .row-fluid
        .span11
          %h2 Art Director
          %h3 Ouray Sportswear
          %h4 March '09 - October '11 (2 years 7 months)
          %p.summary Summary: Hired by PE firm to rebuild creative department of distressed company.

          %p Part of new management team to turnaround bankrupt company and win South Denver’s 2011 Small Business of the Year award. Applied an analytical approach to the creative process which included ongoing trend and market analysis. Developed lean systems for the creative team to meet aggressive deadlines which lead to a company wide adoption of my techniques. Credited with improvements that increased revenues 14%.

      .row-fluid
        .span11
          %h2 Account Executive
          %h3 Futureshirts
          %h4 January '05 - March'08 (3 years 3 months)
          %p.summary Summary: Sell, design, and manage delivery of product to customer.

          %p Company operated as a business within a business. Acquired and managed 60 accounts which grew sales 20%. Responsible to identify new business and manage line plan development. Role required collaborating with freelance design teams and sourcing vendors for accurate, and on-time delivery.
      .row-fluid
        .span11
          %h2 Founder
          %h3 Church Clothes
          %h4 October '00 - December'06 (6 years 3 months)
          %p Initiated and managed all brand activities including creative marketing, multi-channel sales, visual design, merchandising, vendor sourcing, production management, and distribution logistics.




  %section.portfolio#portfolio
    %h1 Websites
    .row-fluid
      .span4
        .websites=image_tag "codejournal.jpg"
      .span4
        .websites=image_tag "catmath.jpg"
      .span4
        .websites=image_tag "paperwhite.jpg"
    .row-fluid
      .span4
        .websites=image_tag "weston.jpg"
      .span4
        .websites=image_tag "oem.jpg"
      .span4
        .websites=image_tag "amb3r.jpg"
    .row-fluid
      .span4
        .websites=image_tag "deb.jpg"
      .span4
        .websites=image_tag "logan.jpg"


    %h1 Logos
    .row-fluid
      .span4
        .websites=image_tag "bird.jpg"
      .span4
        .websites=image_tag "inculcate.jpg"
      .span4
        .websites=image_tag "ruby.jpg"
    .row-fluid
      .span4
        .websites=image_tag "edx.jpg"
      .span4
        .websites=image_tag "dave.jpg"
      .span4
        .websites=image_tag "cats.jpg"

    %h1 Product Lines
    .row-fluid
      .span4
        .websites=image_tag "crocs.jpg"
      .span4
        .websites=image_tag "johnny.jpg"
      .span4
        .websites=image_tag "mtn.jpg"

    %h1 My Patent
    .row-fluid
      .span4
        .websites=image_tag "shirt.jpg"
      .span4
        .websites=image_tag "kids.jpg"
      .span4
        .websites=image_tag "sales.jpg"

%section.bio.row-fluid
  .span6
    %p I sold my company to dive head-first into the world wide web. My broad background means I can contribute to a team in a lot of ways. Ideally I'm looking to join a company that is actively building Ruby on Rails application(s).
  .span1
  .span4.action
    -# Removed <button> and added the .btn class to the <a> instead
    = mail_to "dave@hireDave.me", "Hire Me!", subject: "Let's talk about some work", class: 'btn btn-success hire-me'

%section.merits.row-fluid
  -# These were in a grid that was different from the section
  -# below it, which looked weird. They now line up properly.
  .span3#experience
    %h1 Experience
    %ul
      %li Ruby on Rails Developer
      %li Graphic / Web Designer
      %li Business Owner
      %li Art Director
      %li Finance Director
      %li Sales Manager

  .span3
    %h1 Highlights
    %ul
      %li Winner small business of the year '11
      %li Successful business exit
      %li Masters, Finance
      %li Patent owner
      %li Managed nine graphic artists
      %li Hired ten employees

  .span6.tools
    %h1 Tools
    .row-fluid
      .span7
        %ul
          %li Adobe Creative Suite
          %li balsamiq
          %li HTML5 / HAML
          %li CSS3 / SCSS
          %li Ruby / Rails
          %li Cucumber / RSpec

      .span5
        %ul
          %li Git / Github
          %li Heroku
          %li Microsoft Office
          %li iWork
          %li Basecamp / Trello
          %li Quickbooks

%section.next.row-fluid
  .span3.work-interests
    %h1 Interested in
    %ul
      %li Ruby on Rails Position

  .span3.work-interests
    %h1 Work types
    %ul
      %li Full time
      %li Part time
      %li Contract

  .span3
    %h1 Locations
    %ul
      %li Boulder / Denver
      %li Atlanta
      %li Florida

  .span3
    %h1 Ideal situation
    %ul
      %li Pair programming
      %li Small and passionate team
      %li Learning environment

app/views/main/portfolio.html.haml
%h1 Websites
.row-fluid
  .span4
    .websites=image_tag "codejournal.jpg"

  .span4
    .websites=image_tag "amb3r.jpg"

  .span4
    .websites=image_tag "paperwhite.jpg"
.row-fluid
  .span4
    .websites=image_tag "weston.jpg"
  .span4
    .websites=image_tag "oem.jpg"
  .span4
    .websites=image_tag "deb.jpg"



%h1 Logos
.row-fluid
  .span4
    .websites=image_tag "edx.jpg"
  .span4
    .websites=image_tag "inculcate.jpg"
  .span4
    .websites=image_tag "ruby.jpg"


%h1 Product Lines
.row-fluid
  .span4
    .websites=image_tag "crocs.jpg"
  .span4
    .websites=image_tag "johnny.jpg"
  .span4
    .websites=image_tag "mtn.jpg"

%h1 My Patent
.row-fluid
  .span4
    .websites=image_tag "shirt.jpg"
  .span4
    .websites=image_tag "kids.jpg"
  .span4
    .websites=image_tag "sales.jpg"

app/views/pages/_questionnaire.html.erb
<div id="wufoo-r7x2z1">
Fill out my <a href="http://hiredave.wufoo.com/forms/r7x2z1">online form</a>.
</div>
<script type="text/javascript">var r7x2z1;(function(d, t) {
var s = d.createElement(t), options = {
'userName':'hiredave',
'formHash':'r7x2z1',
'autoResize':true,
'height':'1199',
'async':true,
'header':'show'};
s.src = ('https:' == d.location.protocol ? 'https://' : 'http://') + 'wufoo.com/scripts/embed/form.js';
s.onload = s.onreadystatechange = function() {
var rs = this.readyState; if (rs) if (rs != 'complete') if (rs != 'loaded') return;
try { r7x2z1 = new WufooForm();r7x2z1.initialize(options);r7x2z1.display(); } catch (e) {}};
var scr = d.getElementsByTagName(t)[0], par = scr.parentNode; par.insertBefore(s, scr);
})(document, 'script');</script>

app/views/pages/art.html.haml
%section.work
  %section.left-column
    %section.art.about
      %h1 Art
      = link_to image_tag('dribbble.png'), 'http://www.dribbble.com/davewoodall', target: '_blank'
      %p I’ve worked as graphic designer, web designer, art director, and application UI architect. My favorite projects are those where I can collaborate with other artists.

    %section.showcase.art-portfolio
      %section.aspect
        %h2 Web Design
        %ul
          %li= image_tag 'codejournal.jpg'
          %li= image_tag 'catmath.jpg'
          %li= image_tag 'logan.jpg'
          %li= image_tag 'oem.jpg'
          %li= image_tag 'weston.jpg'

      %section.aspect
        %h2 Logo Design
        %ul
          %li= image_tag 'bird.jpg'
          %li= image_tag 'cats.jpg'
          %li= image_tag 'inculcate.jpg'
          %li= image_tag 'ruby.jpg'

      %section.aspect
        %h2 Product Line Design
        %ul
          %li= image_tag 'crocs.jpg'
          %li= image_tag 'johnny.jpg'
          %li= image_tag 'mtn.jpg'
          %li= image_tag 'sales.jpg'

  %section.sidebar
    .merits
      %h1 Skills
      %ul
        %li Art Direction
        %li Project Planning
        %li Web Design
        %li UX/UI Wire-Framing
        %li Graphic Design
        %li Logo Design

    .action-button
      %ul
        %li Hire me!
        %ul.drawer
          %li= mail_to("dave@hireDave.me", "email", subject: "Let's talk about some work!")
          %li= render 'shared/mention'

%footer
  = render 'shared/nav_social'

app/views/pages/blog.haml
%header
  %h1 The ABC's (Art & Business && Code)
%section.content.services
  .left-bar
    .hero
      %h1 How to start a business
      %h3 Category: Business
    .overview
      %p Let me help build your business by doing whatever needs to get it done. My primary skills are related to Design, Code, and Business Development.

    .code
      %h2 Code
      .grid-row
        %h3#web-apps Web apps
        =link_to "top", "#"

        %h4
          Front End & Rails Developer for
          =link_to "InvitedHome", "http://www.invitedHome.com"
        %h4
          Full Stack Developer for
          =link_to "ScreenPrintly", "http://www.ScreenPrintly.com"
          =link_to "View the source code", "http://www.github.com/woodall/screenprintly"




  .right-bar
    %h3 Tags
    %ul
      %li= link_to "This is the name of a recent post"

app/views/pages/business.html.haml
%section.work
  %section.left-column
    %section.art.about
      %h1 Business
      = link_to image_tag('linkedin.png'), 'http://www.linkedin.com/in/davewoodall', target: '_blank', class: 'linkedin-icon'
      %p Business is a collection of hypotheses to systematically test. The proof is in the profit!

    %section.showcase.art-portfolio

      %section.aspect-hero
        %h2 The Black Box
        %p The goal of business is to grow and sustain itself with self-generated profits. I like to think of it as a black box where we insert $1 and it spits out $10.
        %ul
          %li= image_tag 'black_box.jpg'

      %section.aspect-hero
        %h2 Strategy
        %p I love getting on the chalk board and figuring out how to buy low and sell high. The strategy of taking a natural resource and adding value that customers gladly pay for.
        %ul
          %li= image_tag 'strategy.jpg'

      %section.aspect-hero
        %h2 Operations
        %p Now the fun part. Once we have a business model, I like to focus on how to compete and do it better, faster, and cheaper than the competitors.
        %ul
          %li= image_tag 'operations.jpg'

      %section.aspect
        %h2 Marketing
        %p I'm a fan of packaging concepts and services in a way that makes it easy for customers to make buying decisions.  I developed a menu of services for customers to know the difference between t-shirt inks, and design services.
        %ul
          %li= image_tag 'Blast.gif'
          %li= image_tag 'IL.gif'
          %li= image_tag 'foil.gif'
          %li= image_tag 'SSP.gif'

      %section.aspect
        %h2 Innovation
        %p Daily off-sites are some of my most favorite activities. Getting people in a room to create something new and exciting. Ouray Sportswear need to grow their 'two-tshirt' sales combo. In the process I created the 'flipface', and subsequently received a patent for the idea.
        %ul
          %li= image_tag 'kids.jpg'
          %li= image_tag 'shirt.jpg'



  %section.sidebar
    .merits
      %h1 Skills
      %ul
        %li Customer Development
        %li Sales
        %li Analytical Marketing
        %li Team Management
        %li Corporate Strategy
        %li Finance & Accounting

    .action-button
      %ul
        %li Hire me!
        %ul.drawer
          %li= mail_to("dave@hireDave.me", "email", subject: "Let's talk about some work!")
          %li= render 'shared/mention'

app/views/pages/code.html.haml
%section.work
  %section.left-column
    %section.art.about
      %h1 Code
      = link_to image_tag('github.png'), 'http://www.github.com/davewoodall', target: '_blank', class: 'github-icon'
      %p Have you ever thought of code as a foreign language? Once I saw it from that perspective, I didn’t want to be bound to a translator.

    %section.showcase.art-portfolio
      %section.aspect-row
        %h2 Eye Candy
        %p I love the brain-storm, wireframe, mockup, markup process.
        %ul
          %li= image_tag 'ai.png'
          %li= image_tag 'ps.jpg'
          %li= image_tag 'fw.jpg'
          %li= image_tag 'HTML.png'
          %li= image_tag 'css3.jpg'
          %li= image_tag 'jquery-logo.jpg'

      %section.aspect-row
        %h2 Transactions
        %p Now the fun really begins! Making it all real, validated by transactions!
        %ul
          %li= image_tag 'ruby.png'
          %li= image_tag 'RoR.png'
          %li= image_tag 'github-logo.png'
          %li= image_tag 'heroku.png'

  %section.sidebar
    .merits
      %h1 Skills
      %ul
        %li Wire Framing: AI, PSD, FW
        %li Markup: HTML, HAML
        %li Styling: CSS, SCSS
        %li Behavior: JQuery
        %li Scripting: Ruby, UNIX
        %li Frameworks: Ruby on Rails, Bootstrap

    .action-button
      %ul
        %li Hire me!
        %ul.drawer
          %li= mail_to("dave@hireDave.me", "email", subject: "Let's talk about some work!")
          %li= render 'shared/mention'

%footer
  = render 'shared/nav_social'

app/views/pages/contact.haml
%header
  %h1 Let's see if we're on the same page
%section.content.services
  .left-bar
    = render 'questionnaire'

  .right-bar
    %h3 FAQ's
    %p Will you work for equity?
    %p.answer Depends on the situation.

app/views/pages/index.haml
%header
  %h1 Part-time technical Co-founder for hire
%section.content
  .left-bar
    .hero
      = image_tag "des_biz_code.png"
      %h1 Design, Business, Code
    .copy
      %h4 Ideas and action
      %p Dear entrepreneur,
      %p I started helping companies with design, strategy, and coding after I sold my business.
      %p I enjoy seeing the big picture, brainstorming ideas, and delivering solutions.
      %p I'd love to help grow your company!
      .signature= image_tag "signature.png"
  .right-bar
    = render 'shared/more_than_freelancer'
    = render 'shared/he_can'

    %h3 Recent Note
    =link_to @newest_post.title, "/notes/#{@newest_post.slug}"

app/views/pages/index.html.haml
%header
  %h1 Part-time technical Co-founder for hire
%section.content
  .left-bar
    .hero
      = image_tag "des_biz_code.png"
      %h1 Design, Business, Code
    .copy
      %h4 Ideas and action
      %p Dear entrepreneur,
      %p I started helping companies with design, strategy, and coding after I sold my business.
      %p I enjoy seeing the big picture, brainstorming ideas, and delivering solutions.
      %p I'd love to help grow your company!
      .signature= image_tag "signature.png"
  .right-bar
    .me= image_tag "me.jpg"
    %h2 More than a freelancer
    %p Tired of dealing with multiple people to get something done?

    %h3 Hire Dave! He can...
    %ul
      %li Sketch wireframes
      %li Design logos
      %li Build web apps
      %li Analyze financials
      %li Develop systems
      %li Create work flows
      %li Manage teams
      %li Brainstorm
      %li Talk strategy

    %h4=link_to "See services", services_path

app/views/pages/tshirts.html.haml
%section.work
  %section.left-column
    %section.about-tshirts
      %h1.head Need Tshirts?
      %p.shirt I have been designing & printing shirts for 17 years. My goal is to make the perfect tshirt for you so that it becomes the favorite in your customer’s closet.
      %section.showcase.shirt-summary

        %section.shirt-info.perfect-shirt
          .hero-image= image_tag 'perfectShirt.png'
          %h2 The Perfect Tshirt
          %p The perfect tshirt is a combination of product, process and art.


        %section.shirt-info.shirt-costs
          .hero-image= image_tag 'projectDetails.png'
          %h2 How much do tshirts cost?
          %p Making the perfect shirt requires paying attention to how it looks, fits, and feels. I've found the process works much smoother when you set the budget, in-hand date, and quantity. Then, I'll take care of the fit, feel, and look.

        %section.shirt-info.my-job-as-tshirts
          %h2 Think of me as your personal Fashion Designer
          %p I'll make sure you create the coolest t-shirt within your deadline and budget.

          %ul.shirt-part
            %li= image_tag 'shirt.png'
            %li Vneck, crew neck, tank top? Tell me what kind of shirt you want and I'll find it for you.
          %ul.shirt-part
            %li= image_tag 'ink.png'
            %li Did you know there is more than one type of ink? Oh yeah, there's plastisol, water-base, and discharge, to name a few.
          %ul.shirt-part
            %li= image_tag 'art.png'
            %li I can handle art, or advise the artist on best ways to design for your budget.

        %section.shirt-info.my-job-as-artist
          %h2 How I Design
          %p 1. Get an idea of what you like.
          %p 2. Sketch a concept for your approval.
          %p 3. Design final art.
          %p Art Rate: $75 an hr. / Average design cost: $200

        %section.shirt-info.my-job-as-artist
          %a{name: "get-started"}
          %h2 Ready?
          %p Fill out a form and we're in motion!
          = render 'shared/wufoo'



  %section.sidebar
    .action-button
      %ul
        %li= link_to "Tshirt trends", "http://pinterest.com/hireDave/pins/"

    .action-button
      %ul
        %li Let's print a Tshirt!
        %ul.drawer
          %li= render 'shared/wufoo'




%footer
  = render 'shared/nav_social'

app/views/posts/index.haml
%section.work
  %section.left-column
    %h1 A blog

    - @post.each do |post|
      %p= post.title


%footer
  = render 'shared/nav_social'

app/views/posts/show.html.haml
%section.work
  %section.left-column
    %h1= @post.title
    %p= @post.body
    %p= @post.tags


%footer
  = render 'shared/nav_social'

app/views/shared/_footer.haml
%footer
  .status.col
    %h3 Status
    %p.availability As of #{ Time.now.strftime("%B, %e") } <br> I'm available for 20 - 30 hrs a month
    %p.rate $75 hr.
  .contact.col
    %h3 Contact
    %ul
      %li= mail_to 'dave@hireDave.me'
      %li 303 416 7032
      %li Boulder, CO
  .social.col
    %h3 Social
    %ul
      %li= link_to 'dribbble', "http://dribbble.com/davewoodall", target: "_blank"
      %li= link_to 'github', "https://github.com/woodall/", target: "_blank"
      %li= link_to 'twitter', "https://www.twitter.com/hireDave", target: "_blank"
      %li= link_to 'facebook', "https://www.facebook.com/hireDave", target: "_blank"
      %li= link_to 'linkedIn', "http://www.linkedin.com/in/davewoodall", target: "_blank"
  .col
    %h3 Site map
    %ul
      %li= link_to 'home', root_path
      %li= link_to 'services', services_path
      %li= link_to 'notes', blogposts_path
      %li= link_to 'contact Dave', contact_path

app/views/shared/_he_can.haml
%h3 Hire Dave! He can...
%ul
  %li Brainstorm
  %li Talk strategy
  %li Sketch wireframes
  %li Develop systems
  %li Create work flows
  %li Design logos
  %li Build web apps
  %li Analyze financials
  %li Manage teams

%h4=link_to "See services", services_path

app/views/shared/_more_than_freelancer.haml
.me= image_tag "me.jpg"
%h2 More than a freelancer
%p Tired of dealing with multiple people to get something done?

app/views/shared/_nav.haml
%nav
  .logo
    =link_to image_tag('logo.png'), root_path
  .nav
    %ul
      %li= link_to 'services', services_path
      %li= link_to 'notes', 'http://dave.woodalls.me', target: '_blank'
      %li= link_to 'contact Dave', contact_path

app/views/shared/_typekit.html.erb
<script type="text/javascript" src="//use.typekit.net/ipn2fnt.js"></script>
<script type="text/javascript">try{Typekit.load();}catch(e){}</script>